getwd()
setwd('C:/Users/akshithreddy/Downloads')
states<- read.csv('stateData.csv')
states
statesubset <- subset(states, state.region == 1)
head(statesubset, 2)
dim(statesubset)
install.packages("rmarkdown")
?mtcars
summary(mtcars)
str(mtcars)
subset(mtcars, mpg>= 30 | hp < 60)
install.packages("ggplot2", dependencies = T)
library(ggplot2)
install.packages('xlsx')
library(xlsx)
install.packages('rJava')
library(xlsx)
library(rJava)
install.packages('rJava')
library(rJava)
install.packages('dplyr')
library(dplyr)
install.packages('ggvis')
library(ggvis)
